{{ if .Values.authgear.analytic.cronjob.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authgear.nameAnalyticCronWeeklyScript" . | quote }}
data:
  entrypoint.sh: |-
    #!/bin/bash

    set -e

    authgear-portal analytic collect-count last-week

    {{- if .Values.authgear.analytic.googleSpreadsheet.enabled }}
    authgear-portal analytic report user \
      --period=last-week \
      --google-client-credentials-file={{ .Values.authgear.analytic.googleSpreadsheet.secret.mountPath }}/client_credentials.json \
      --google-token-file={{ .Values.authgear.analytic.googleSpreadsheet.secret.mountPath }}/token.json \
      --output-type=google-sheets \
      --google-spreadsheet-id={{ .Values.authgear.analytic.googleSpreadsheet.id | quote }} \
      --google-spreadsheet-range={{ .Values.authgear.analytic.googleSpreadsheet.range.userWeeklyReport | quote }}

    authgear-portal analytic report project \
      --period=last-week \
      --google-client-credentials-file={{ .Values.authgear.analytic.googleSpreadsheet.secret.mountPath }}/client_credentials.json \
      --google-token-file={{ .Values.authgear.analytic.googleSpreadsheet.secret.mountPath }}/token.json \
      --output-type=google-sheets \
      --google-spreadsheet-id={{ .Values.authgear.analytic.googleSpreadsheet.id | quote }} \
      --google-spreadsheet-range={{ .Values.authgear.analytic.googleSpreadsheet.range.projectWeeklyReport | quote }}
    {{- end }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "authgear.nameAnalyticCronWeekly" . | quote }}
  labels:
    {{- include "authgear.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.authgear.analytic.cronjob.weeklySchedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: authgear-analytic-cronjob-weekly
            image: {{ .Values.authgear.portalServer.image | quote }}
            command:
            - sh
            - /bin/entrypoint.sh
            volumeMounts:
            - name: script-configmap-volume
              mountPath: /bin/entrypoint.sh
              readOnly: true
              subPath: entrypoint.sh
            {{- if .Values.authgear.analytic.googleSpreadsheet.enabled }}
            - name: google-sheets-secret-volume
              mountPath: {{ .Values.authgear.analytic.googleSpreadsheet.secret.mountPath | quote }}
            {{- end }}
            env:
            - name: DATABASE_URL
              value: {{ .Values.authgear.databaseURL | quote }}
            - name: DATABASE_SCHEMA
              value: {{ .Values.authgear.databaseSchema | quote }}
            - name: AUDIT_DATABASE_URL
              value: {{ .Values.authgear.auditLog.databaseURL | quote }}
            - name: AUDIT_DATABASE_SCHEMA
              value: {{ .Values.authgear.auditLog.databaseSchema | quote }}
            - name: ANALYTIC_REDIS_URL
              value: {{ .Values.authgear.analytic.redisURL | quote }}
          restartPolicy: Never
          volumes:
          - name: script-configmap-volume
            configMap:
              defaultMode: 0755
              name: {{ include "authgear.nameAnalyticCronWeeklyScript" . | quote }}
          {{- if .Values.authgear.analytic.googleSpreadsheet.enabled }}
          - name: google-sheets-secret-volume
            {{- toYaml .Values.authgear.analytic.googleSpreadsheet.secret.volume | nindent 12 }}
          {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authgear.nameAnalyticCronMonthlyScript" . | quote }}
data:
  entrypoint.sh: |-
    #!/bin/bash

    set -e

    authgear-portal analytic collect-count last-month

    {{ if .Values.authgear.analytic.googleSpreadsheet.enabled }}
    authgear-portal analytic report project \
      --period=last-month \
      --google-client-credentials-file={{ .Values.authgear.analytic.googleSpreadsheet.secret.mountPath }}/client_credentials.json \
      --google-token-file={{ .Values.authgear.analytic.googleSpreadsheet.secret.mountPath }}/token.json \
      --output-type=google-sheets \
      --google-spreadsheet-id={{ .Values.authgear.analytic.googleSpreadsheet.id | quote }} \
      --google-spreadsheet-range={{ .Values.authgear.analytic.googleSpreadsheet.range.projectMonthlyReport | quote }}
    {{ end }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "authgear.nameAnalyticCronMonthly" . | quote }}
  labels:
    {{- include "authgear.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.authgear.analytic.cronjob.monthlySchedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: authgear-analytic-cronjob-monthly
            image: {{ .Values.authgear.portalServer.image | quote }}
            command:
            - sh
            - /bin/entrypoint.sh
            volumeMounts:
            - name: script-configmap-volume
              mountPath: /bin/entrypoint.sh
              readOnly: true
              subPath: entrypoint.sh
            {{- if .Values.authgear.analytic.googleSpreadsheet.enabled }}
            - name: google-sheets-secret-volume
              mountPath: {{ .Values.authgear.analytic.googleSpreadsheet.secret.mountPath | quote }}
            {{- end }}
            env:
            - name: DATABASE_URL
              value: {{ .Values.authgear.databaseURL | quote }}
            - name: DATABASE_SCHEMA
              value: {{ .Values.authgear.databaseSchema | quote }}
            - name: AUDIT_DATABASE_URL
              value: {{ .Values.authgear.auditLog.databaseURL | quote }}
            - name: AUDIT_DATABASE_SCHEMA
              value: {{ .Values.authgear.auditLog.databaseSchema | quote }}
            - name: ANALYTIC_REDIS_URL
              value: {{ .Values.authgear.analytic.redisURL | quote }}
          restartPolicy: Never
          volumes:
          - name: script-configmap-volume
            configMap:
              defaultMode: 0755
              name: {{ include "authgear.nameAnalyticCronMonthlyScript" . | quote }}
          {{- if .Values.authgear.analytic.googleSpreadsheet.enabled }}
          - name: google-sheets-secret-volume
            {{- toYaml .Values.authgear.analytic.googleSpreadsheet.secret.volume | nindent 12 }}
          {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authgear.nameAnalyticCronDailyScript" . | quote }}
data:
  entrypoint.sh: |-
    #!/bin/bash

    set -e

    authgear-portal analytic collect-count yesterday
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ include "authgear.nameAnalyticCronDaily" . | quote }}
  labels:
    {{- include "authgear.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.authgear.analytic.cronjob.dailySchedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: authgear-analytic-cronjob-daily
            image: {{ .Values.authgear.portalServer.image | quote }}
            command:
            - sh
            - /bin/entrypoint.sh
            volumeMounts:
            - name: script-configmap-volume
              mountPath: /bin/entrypoint.sh
              readOnly: true
              subPath: entrypoint.sh
            env:
            - name: DATABASE_URL
              value: {{ .Values.authgear.databaseURL | quote }}
            - name: DATABASE_SCHEMA
              value: {{ .Values.authgear.databaseSchema | quote }}
            - name: AUDIT_DATABASE_URL
              value: {{ .Values.authgear.auditLog.databaseURL | quote }}
            - name: AUDIT_DATABASE_SCHEMA
              value: {{ .Values.authgear.auditLog.databaseSchema | quote }}
            - name: ANALYTIC_REDIS_URL
              value: {{ .Values.authgear.analytic.redisURL | quote }}
          restartPolicy: Never
          volumes:
          - name: script-configmap-volume
            configMap:
              defaultMode: 0755
              name: {{ include "authgear.nameAnalyticCronDailyScript" . | quote }}
{{ end }}
