{{ if .Values.authgear.auditLog.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "authgear.nameAuditLogCron" . | quote }}
  labels:
    {{- include "authgear.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.authgear.auditLog.cronjob.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          {{- if .Values.authgear.mainServer.nodeSelector }}
          nodeSelector:
            {{- .Values.authgear.mainServer.nodeSelector | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.authgear.mainServer.nodeName }}
          nodeName: {{ .Values.authgear.mainServer.nodeName | quote }}
          {{- end }}
          {{- if .Values.authgear.mainServer.affinity }}
          affinity:
            {{- .Values.authgear.mainServer.affinity | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.authgear.mainServer.tolerations }}
          tolerations:
          {{- .Values.authgear.mainServer.tolerations | toYaml | nindent 10 }}
          {{- end }}
          {{- if .Values.authgear.mainServer.topologySpreadConstraints }}
          topologySpreadConstraints:
          {{- .Values.authgear.mainServer.topologySpreadConstraints | toYaml | nindent 10 }}
          {{- end }}
          {{- if .Values.authgear.extraVolumes }}
          volumes:
          {{- toYaml .Values.authgear.extraVolumes | nindent 10 }}
          {{- end }}
          containers:
          - name: authgear-audit-log-cronjob
            image: {{ .Values.authgear.mainServer.image | quote }}
            imagePullPolicy: Always
            args: ["authgear", "audit", "database", "maintain"]
            env:
            - name: DATABASE_URL
              value: {{ .Values.authgear.auditLog.databaseURL | quote }}
            - name: DATABASE_SCHEMA
              value: {{ .Values.authgear.auditLog.databaseSchema | quote }}
            {{- if .Values.authgear.extraVolumeMounts }}
            volumeMounts:
            {{- toYaml .Values.authgear.extraVolumeMounts | nindent 12 }}
            {{- end }}
          restartPolicy: Never
{{ end }}
