apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "authgear.nameDeno" . | quote }}
  labels:
    {{- include "authgear.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.authgear.deno.replicas }}
  selector:
    matchLabels:
      {{- include "authgear.denoSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "authgear.denoSelectorLabels" . | nindent 8 }}
    spec:
      {{- if .Values.authgear.deno.nodeSelector }}
      nodeSelector:
        {{- .Values.authgear.deno.nodeSelector | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.authgear.deno.nodeName }}
      nodeName: {{ .Values.authgear.deno.nodeName | quote }}
      {{- end }}
      {{- if .Values.authgear.deno.affinity }}
      affinity:
        {{- .Values.authgear.deno.affinity | toYaml | nindent 8 }}
      {{- end }}
      {{- if .Values.authgear.deno.tolerations }}
      tolerations:
      {{- .Values.authgear.deno.tolerations | toYaml | nindent 6 }}
      {{- end }}
      {{- if .Values.authgear.deno.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- .Values.authgear.deno.topologySpreadConstraints | toYaml | nindent 6 }}
      {{- end }}
      containers:
      - name: authgear-deno
        image: {{ .Values.authgear.deno.image | quote }}
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 8090
          protocol: TCP
        resources:
          {{- toYaml .Values.authgear.deno.resources | nindent 10 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "authgear.nameDeno" . | quote }}
  labels:
    {{- include "authgear.labels" . | nindent 4 }}
spec:
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "authgear.denoSelectorLabels" . | nindent 4 }}
{{- if .Values.authgear.deno.hpa.enabled }}
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "authgear.nameDeno" . | quote }}
spec:
  minReplicas: {{ .Values.authgear.deno.replicas }}
  maxReplicas: {{ .Values.authgear.deno.hpa.maxReplicas }}
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "authgear.nameDeno" . | quote }}
  metrics:
    {{- toYaml .Values.authgear.deno.hpa.metrics | nindent 4 }}
{{- end }}
