{{ if .Values.authgear.stripe.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "authgear.nameUploadStripeCron" . | quote }}
  labels:
    {{- include "authgear.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.authgear.stripe.cronjob.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          {{- if .Values.authgear.portalServer.nodeSelector }}
          nodeSelector:
            {{- .Values.authgear.portalServer.nodeSelector | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.authgear.portalServer.nodeName }}
          nodeName: {{ .Values.authgear.portalServer.nodeName | quote }}
          {{- end }}
          {{- if .Values.authgear.portalServer.affinity }}
          affinity:
            {{- .Values.authgear.portalServer.affinity | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.authgear.portalServer.tolerations }}
          tolerations:
          {{- .Values.authgear.portalServer.tolerations | toYaml | nindent 10 }}
          {{- end }}
          {{- if .Values.authgear.portalServer.topologySpreadConstraints }}
          topologySpreadConstraints:
          {{- .Values.authgear.portalServer.topologySpreadConstraints | toYaml | nindent 10 }}
          {{- end }}
          {{- if .Values.authgear.extraVolumes }}
          volumes:
          {{- toYaml .Values.authgear.extraVolumes | nindent 10 }}
          {{- end }}
          containers:
          - name: authgear-upload-stripe-cronjob
            image: {{ .Values.authgear.portalServer.image | quote }}
            imagePullPolicy: Always
            args: ["authgear-portal", "pricing", "upload-usage-to-stripe", "--all"]
            env:
            - name: DATABASE_URL
              value: {{ .Values.authgear.databaseURL | quote }}
            - name: DATABASE_SCHEMA
              value: {{ .Values.authgear.databaseSchema | quote }}
            - name: STRIPE_SECRET_KEY
              value: {{ .Values.authgear.stripe.secretKey | quote }}
            - name: SENTRY_DSN
              value: {{ .Values.authgear.sentryDSN | quote }}
            {{- if .Values.authgear.extraVolumeMounts }}
            volumeMounts:
            {{- toYaml .Values.authgear.extraVolumeMounts | nindent 12 }}
            {{- end }}
{{ end }}
