{{ if .Values.authgear.usageRecord.cronjob.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "authgear.nameUsageRecordCron" . | quote }}
data:
  entrypoint.sh: |-
    #!/bin/bash

    set -e

    authgear-portal usage collect-count active-user this-month
    authgear-portal usage collect-count sms-sent yesterday
    authgear-portal usage collect-count email-sent yesterday
    authgear-portal usage collect-count {{ .Values.authgear.usageRecord.whatsapp.event }} yesterday
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "authgear.nameUsageRecordCron" . | quote }}
  labels:
    {{- include "authgear.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.authgear.usageRecord.cronjob.schedule | quote }}
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: Never
          volumes:
          - name: script-configmap-volume
            configMap:
              defaultMode: 0755
              name: {{ include "authgear.nameUsageRecordCron" . | quote }}
          {{- if .Values.authgear.extraVolumes }}
          {{- toYaml .Values.authgear.extraVolumes | nindent 10 }}
          {{- end }}
          {{- if .Values.authgear.portalServer.nodeSelector }}
          nodeSelector:
            {{- .Values.authgear.portalServer.nodeSelector | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.authgear.portalServer.nodeName }}
          nodeName: {{ .Values.authgear.portalServer.nodeName | quote }}
          {{- end }}
          {{- if .Values.authgear.portalServer.affinity }}
          affinity:
            {{- .Values.authgear.portalServer.affinity | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.authgear.portalServer.tolerations }}
          tolerations:
          {{- .Values.authgear.portalServer.tolerations | toYaml | nindent 10 }}
          {{- end }}
          {{- if .Values.authgear.portalServer.topologySpreadConstraints }}
          topologySpreadConstraints:
          {{- .Values.authgear.portalServer.topologySpreadConstraints | toYaml | nindent 10 }}
          {{- end }}
          containers:
          - name: authgear-usage-record-cronjob
            image: {{ .Values.authgear.portalServer.image | quote }}
            imagePullPolicy: Always
            args: ["sh", "/bin/entrypoint.sh"]
            volumeMounts:
            - name: script-configmap-volume
              mountPath: /bin/entrypoint.sh
              readOnly: true
              subPath: entrypoint.sh
            {{- if .Values.authgear.extraVolumeMounts }}
            {{- toYaml .Values.authgear.extraVolumeMounts | nindent 12 }}
            {{- end }}
            env:
            - name: DATABASE_URL
              value: {{ .Values.authgear.databaseURL | quote }}
            - name: DATABASE_SCHEMA
              value: {{ .Values.authgear.databaseSchema | quote }}
            - name: AUDIT_DATABASE_URL
              value: {{ .Values.authgear.auditLog.databaseURL | quote }}
            - name: AUDIT_DATABASE_SCHEMA
              value: {{ .Values.authgear.auditLog.databaseSchema | quote }}
            - name: ANALYTIC_REDIS_URL
              value: {{ .Values.authgear.analytic.redisURL | quote }}
            - name: SENTRY_DSN
              value: {{ .Values.authgear.sentryDSN | quote }}
{{ end }}
